version: 2.1

orbs:
  heroku: circleci/heroku@2.0.0
workflows:
    example-workflow:
      jobs:
        - heroku/deploy-via-git:
            api-key: b95ab31d-8738-49ec-916a-009ea2d1c276
            app-name: Vue forum
            branch: master